### ISSUE TITLE
Still locking up, then shutting down....

### ISSUE THREAD

**Issue by jonesinecuador** [steveschow/gfxCardStatus#10]
I still cannot find a version of gfxcardstatus that will let me go to "integrated only," even trying the modified versions. I am shut down in the latest version when attempting to switch modes.  I am on a MBP 15", Early 2011 running MacOS Sierra Version 10.12.2, clean install on formatted drive.  It is an issues as any Flash cause a hard crash.

Of gfxcardstautus, I have tried 1.7, 2.3, 2.4.2i, 2.4.3i. 

Is there one version that I have missed or any other workarounds? I have been reading this thread and didn't see anything, but could have missed.

Thanks in advance for your help!

**Comment by steveschow** [comment]
2.4.3i is the last one.  when you say "when attempting to switch modes", what do you mean exactly?

**Comment by staska012** [comment]
+1 ! 
can't find that version can stick "Integrated only" 
i'm on Late 2011, clean 10.9.5
