### ISSUE TITLE
This app saved my Mac

### ISSUE THREAD

**Issue by chrislombardoau** [steveschow/gfxCardStatus#12]
Hi mates,

I've recently purchased a MacBook Pro Mid-2010 second hand and the seller didn't tell me the laptop was faulty.
I found gfxCardStatus and now the Mac works perfectly, no more kernel panics, I keep using it with Integrated Graphics Only.

Thanks 👍 🥇

**Comment by steveschow** [comment]
Thanks for the feedback.  closing issue.
