### ISSUE TITLE
kernel panics

### ISSUE THREAD

**Issue by yasmin85** [steveschow/gfxCardStatus#13]
mbpro 2010 keeps going to black screen and restarting.
also kernel panics and now i cannot keep safari open without crashing for more than 3 seconds.

apple communities sent me to this site but I'm totally lost on what i am supposed to do. please help . i can send a copy of kernel panic reports, crash rep, and or etre check . let me know pleeeeease.

**Comment by steveschow** [comment]
On the readme for the project there is a section called "Binary Releases".  Follow the link there to download the software.  Run the software and select integrated-only from the pull down menu.  The pull down menu appears in the menu as an n or an i, depending on the mode you're in.  You will have to manually select integrated-only every time you start the software.  Apple should point people to the binary release page

**Comment by byvlad** [comment]
Excuse me, is it works with os 10.12 and mpb pro 2011? because my discrete gpu is fault.

**Comment by steveschow** [comment]
closing as non-issue, readme explains what to do.
