### ISSUE TITLE
sudo nvram fa4ce28d-b62f-4c99-9cc3-6815686e30f9:gpu-power-prefs=%01%00%00%00

### ISSUE THREAD

**Issue by nsgrbr** [steveschow/gfxCardStatus#18]
If you are unable to get to the login screen because Mac OS freezes. Try this procedure.

Macbook Pro Early 2011 - Intel HD 3000 and AMD Radeon HD 6750M - Mac OS Sierra 10.12.5

Test: Single-User mode (Command + S) with red background screen and white stripes.

After the reboot, the screen became normal again.
The configuration remains after 3 days with 3 shutdowns.

**sudo nvram fa4ce28d-b62f-4c99-9cc3-6815686e30f9:gpu-power-prefs=%01%00%00%00**

. . . . . 
There is this procedure that works but some people could not do it through ArchLinux.

AppleMacFinder
https://forums.macrumors.com/threads/force-2011-macbook-pro-8-2-with-failed-amd-gpu-to-always-use-intel-integrated-gpu-efi-variable-fix.2037591/

FGuarani
https://forums.macrumors.com/threads/force-2011-macbook-pro-8-2-with-failed-amd-gpu-to-always-use-intel-integrated-gpu-efi-variable-fix.2037591/page-5
.
So I decided to search and found that the format "gpu-power-prefs=%01%00%00%00" is not in the correct format.

The correct format is:

**sudo nvram GUID:NVRAM_Variable=value**

GUID - Standard Apple Macbook Pro Early 2011-> fa4ce28d-b62f-4c99-9cc3-6815686e30f9

NVRAM Variable -> gpu-power-prefs

Value for Integrated gpu - In this case Binary data Hexadecimal (%) -> %01%00%00%00
.
**Macbook Pro 2011 (AMD) and Macbook Pro 2014 (Nvidia) have the same GUIDs / UUIDs. I think it's an Apple standard factory.**

FA4CE28D-B62F-4C99-9CC3-6815686E30F9:gpu-active

FA4CE28D-B62F-4C99-9CC3-6815686E30F9:gpu-power-prefs

7C436110-AB2A-4BBB-A880-FE41995C9F8:gpu-policy

https://github.com/ah-/gmux-scripts/issues/1#issuecomment-68113930
.
**Setting NVRAM Variables from OS X - Wikileaks**
Example: DriverOrder

sudo nvram 8BE4DF61-93CA-11D2-AA0D-00E098032B8C:DriverOrder=%00%50

https://wikileaks.org/ciav7p1/cms/page_26968084.html

http://www.insanelymac.com/forum/topic/291655-ozmosis/page-3

https://github.com/erikberglund/AppleNVRAM

**Comment by iceman60** [comment]
Love this tips!
