### ISSUE TITLE
Shows Discrete and Integrated at the same time

### ISSUE THREAD

**Issue by Meligy** [steveschow/gfxCardStatus#6]
When I switch to Integrated Only, I get this:

![2016-09-22_20-16-59](https://cloud.githubusercontent.com/assets/171637/18744547/d90053ae-8101-11e6-9ef6-ca2afce3e108.png)

This is using the app file in the release https://github.com/steveschow/gfxCardStatus/releases/tag/2.4.1i

Machine Version Information:

```
macOS Sierra
10.12 (16A323)

MacBook Pro (Retina, 15-inch, Mid 2014)
```

**Comment by steveschow** [comment]
I can't seem to replicate this problem.  If and when I upgrade to Sierra I will come back to this.

**Comment by steveschow** [comment]
I believe this is fixed by 2.4.2i.  Please try it and let me know, will close this ticket after I get confirmation that problem is solved.

https://github.com/steveschow/gfxCardStatus/releases/tag/v2.4.2i

**Comment by Chamiu** [comment]
I tried 2.4.2i.
10.12.1PB1 (16B2333a) on MacBook Pro 15in Early 2011.
Issue equal @Meligy.
1. install 2.4.2i.
2. launch 2.4.2i.
3. 2.4.2i display at "Dynamic Switching", iStat Menus display "I".
4. select "Integrate Only".
   But 2.4.2i display at "Discrete Only", iStat Menus display "A".

**Comment by steveschow** [comment]
Unfortunately I will not be able to support macs 2011 and newer on Sierra unless Cody updates gfxCardStatus as needed to support the those MBP's.  Something changed in sierra that breaks gfxCardStatus with 2011+ macs.   I will leave this ticket open just in case anyone comes up with a fix.  I've tried several things and basically I'm shooting in the dark.  I don't have a 2011+ mac to test with either.

**Comment by Meligy** [comment]
Hello,
I tested the latest version 2.4.2i both from email and releases tab here. Thanks for spending time on this although it feels blind without having the actual OS.

It seems the same though.

What happens:
1. App opens on dynamic option
2. I switch to integrated
3. App shows the picture shown in this issue after switching
4. I quit and open again
5. App opens on dynamic option again

Maybe the app confusion is a side effect of not being able to switch to non-dynamic integrated graphics.

**Comment by steveschow** [comment]
unfortunately I cannot support 2011 and newer mac's on sierra.  Maybe in the future.  Sorry.

**Comment by Chamiu** [comment]
@steveschow I reported [codykrieger's issue](https://github.com/codykrieger/gfxCardStatus/issues/240#issuecomment-251016524)
2.4.3-test2 work fine that on macOS Sierra.1 PB1 on MacBook Pro Early 2011 (15in)

**Comment by steveschow** [comment]
Ok, well try this release for a while.  please let me know if you have any problems

https://github.com/steveschow/gfxCardStatus/releases/tag/v2.4.3i

**Comment by Meligy** [comment]
@steveschow this [one](https://github.com/steveschow/gfxCardStatus/releases/tag/v2.4.3i) you just uploaded looks very promising.

When I switch to integrated only, I can see that reflected in the menu.

An interesting behaviour though is that, still, when I close the app and reopen, I see it set to dynamic switching, which I'm not sure if it's the normal behaviour of the app, or if this means it's not really switching to integrated only or what.

**Comment by steveschow** [comment]
Unfortuately that is the normal behavior of the app.  I have a tentative plan to add this capability to this fork, but its rather involved in order to do it safely.  You can follow this issue to see if and when it gets done: https://github.com/steveschow/gfxCardStatus/issues/3

But for now you will have to select integrated-only whenever you restart the app.

**Comment by Meligy** [comment]
Actually, I had the app set to integrated, then ran Parallels, and then closed the app and reopened (not to test this, I just moved it to Applications folder to use permanently), and then I saw the "n" letter in the menubar, turned out it switched to discrete graphics.

So, I think it reports moving to integrated, but it really stayed on dynamic switching.

**Comment by steveschow** [comment]
check it again, I am not getting that behavior.

gfxCardStatus always has to start up in dynamic switching mode.  You have to manually change it to integrated-only every time you restart the app.

**Comment by steveschow** [comment]
I believe this issue is fixed, closing ticket.
