### ISSUE TITLE
v2.4.3i

### ISSUE THREAD

**Issue by zamoragreen** [steveschow/gfxCardStatus#7]
I have been using v2.4.3i in order to solve the problem of being unable to switch to integrated only on OSX Sierra, but now gfxCardStatus won't open at startup, no matter how many times I set it to in the preferences

**Comment by steveschow** [comment]
Hmm strange, I'm not having that behavior and I can't think of any reason why the changes I made would effect startup at all.  check the console logs to see if there is anything of a clue there.  I know there is a way to make gfxCardStatus produce its own logs also, but I'm actually not sure how to do that, we'd have to ask Cody.  I will keep this ticket open until we learn more, but I'm afraid I have no idea what is going on there in order to be able to bring you a fix at this time.

**Comment by sikaco** [comment]
My macbook is mid-2015 with AMD graphic, OS is Sierra. I find that if external display was connected, gfxCardStatus will change to discrete card. Except for that everything is perfect.

Actually, this "feature" also good. I just be curious about it is a "feature" or a "bug"?
THX much, your edition is great.

**Comment by steveschow** [comment]
unfortunately that is expected behavior.  External monitors require discrete graphics, period.  Nothing we can do about it as I understand it.

**Comment by sikaco** [comment]
In previous gfxCardStatus edition on previous OS (e.g: Yosemite), it didn't change graphic to discrete graphic if you choose integrated card before connecting external display (also, external display doesn't work). So, this behavior make me confused. 

THX much.

**Comment by steveschow** [comment]
if you were using a version older then 2.3 then it had a bug where it was switching on discrete and leaving integrated also on or something like that.  cody has documented this behavior numerous times on the main gfxcardstatus page and 2.3 fixes the bug so will show discrete.  go read about it there.  this fork is not doing that much and should not effect external monitor.  you have to ask cody about it on the main code.  however i am sure he will tell you what i told you.

**Comment by sikaco** [comment]
Got it. THX for your answer

**Comment by zamoragreen** [comment]
My previous issue where gfxCardStatus wouldn't open on logic seemed to fix itself, and I didn't do anything to change it.

**Comment by namar0x0309** [comment]
Works on 10.12.2 Beta (16C32f)

**Comment by adamrumjahn** [comment]
Hi, I'm using a Macbook Pro mid 2010 with Sierra and it seems that it still keeps switching to discrete.  I installed the 2.4.3i integrated only, so I'm not sure why discrete is still available and why it keeps on switching.  Every time it switches it shuts down. 

Did I not uninstall properly the previous versions?  Please let me know if I'm doing something wrong.  Would really love to get my MBP working again.

**Comment by steveschow** [comment]
you have to manually select integrated-only mode from the pull down menu every time you start up gfxCardStatus.  Hope to fix that in the future.

**Comment by adamrumjahn** [comment]
Yup, been doing that.. but for some reason it still keeps switching.

**Comment by steveschow** [comment]
please provide more information about how and when its switching, describe the exact behavior.

**Comment by kpneas** [comment]
I am having a similar issue as innovo3d. MBP Mid 2010; Sierra Version 10.12.4; When using Chrome Version 58.0.3029.81 I will get a kernal panic while perusing some websites ( BBC, Ebay, and otheres). Also, when I close Chrome, the card status changes quickly to "d" and then back to "i" again. Sometimes, this will cause a panic. 

Please let me know if more info is needed. 

Thank you for any help. And thank you to those updating this most useful app. Without it, this MBP would be not be usable.

**Comment by steveschow** [comment]
Unfortunately, there is nothing that can be done (that i know of), to eliminate the quick little status change to "d' and back to "i', that you have noted.  This is documented in the readme for this project.  My understanding is that Apple is forcing  stuff to discrete mode when exiting some (or all?) apps.  you will see that little "d" to "i" switch happen pretty much every time you quit an app.  

One of the main differences between 2.3 and 2.4.3i is that 2.3 does not change back to "i" when closing apps.  Apple will force it to "d" and then it will stay there on "d" in discrete-only mode (even though the user had requested integrate-only mode).  The main point of this 2.4.3i fork, in fact, is to make sure that at least in that case it will switch back to "i"  and integrated-only mode as soon as possible without getting stuck in discrete-only mode.

Unfortunately I don't know of any way to avoid that that short switch to "d", its something Apple is doing for some strange reason when quitting apps.

A lot of people have had problems with Chrome and its not clear what is happening but I would avoid Chrome with your 2010 MBP.  I'm also still on El Capitan with mine and until I stop hearing from people with problems running Sierra, I will be staying on El Capitan.

**Comment by kpneas** [comment]
Thank you for prompt reply. I really appreciate it. 

It’s more clear to me now, that 2.4.3i does not prevent the quick change to “d”. I had misunderstood. It is working well at sending it back over to integrated. I will give good old Safari a try and see if I still have issues. Unfortunately, perhaps I’ll back up my data and return to El Capitan. 

Thanks again
